### ISSUE TITLE
New Idea: Keep Buy page usable by adding list of exchanges and allowing people to donate Cheems to the contract

### ISSUE THREAD

**Issue by soulthunk** [cryptocheems/cheemscoin#16]
**Is your feature request related to a problem? Please describe.**
I don't like seeing stuff that can't be used anymore.

**Describe the solution you'd like**
I would like it so that there is a list of other exchanges below the main buy utility, as well as a way for people to donate Cheems to the contract so it can still be used.

**Describe alternatives you've considered**
We could just hide the page, but that would be boring.

**Potential applications to use for idea**
Just a simple pop-up in the wallet.

**Additional context**
None.

- [X] By checking this, you have read the Contributing Guidelines page.

**Comment by kowasaur** [comment]
I agree we should not leave the buy page in its current state. I don't want to refill the contract because it really just existed to be used to get money for liquidity so we don't need it anymore. The price also only changes manually so it would essentially create a cap on the price since if the price on say Honeyswap got more than the price on the buy page, you could just buy on there and sell on Honeyswap for free money, driving the price down in the process. If you do want to donate to the buy page you just have to send Cheemscoin here https://blockscout.com/xdai/mainnet/address/0x3A38c400C56927d61f9e02b13868FDfE10cd5330/

Anyways I agree the buy page should have a list of all the exchanges. I also think it should have a basic tutorial on how to buy Cheemscoin (starting with fiat). Maybe a video for that could be cool?

**Comment by SoulRepo** [comment]
> 
> 
> I agree we should not leave the buy page in its current state. I don't want to refill the contract because it really just existed to be used to get money for liquidity so we don't need it anymore. The price also only changes manually so it would essentially create a cap on the price since if the price on say Honeyswap got more than the price on the buy page, you could just buy on there and sell on Honeyswap for free money, driving the price down in the process. If you do want to donate to the buy page you just have to send Cheemscoin here https://blockscout.com/xdai/mainnet/address/0x3A38c400C56927d61f9e02b13868FDfE10cd5330/
> 
> Anyways I agree the buy page should have a list of all the exchanges. I also think it should have a basic tutorial on how to buy Cheemscoin (starting with fiat). Maybe a video for that could be cool?

Yep, a video would be good, like a guide for how to use Ramp or something and then show how to convert it to Cheemscoin. We could also put like a donate button that allows people to donate Cheemscoin easier, and try to automate the price by making a simple script that averages all the prices of the exchanges and makes it into one single price, which removes the problem with the price cap.

**Comment by kowasaur** [comment]
Sorry I probably should have just said that the buy page is also bad because 
1. price doesn't move when you buy on it so the price would never increase if people used it
2. the Cheemscoin needs to be supplied from somewhere and I want to use the Cheemscoin for other things (namely, yield farming)
It just is inferior to any dex in like every way.

**Comment by SoulRepo** [comment]
> 
> 
> Sorry I probably should have just said that the buy page is also bad because
> 
>     1. price doesn't move when you buy on it so the price would never increase if people used it
> 
>     2. the Cheemscoin needs to be supplied from somewhere and I want to use the Cheemscoin for other things (namely, yield farming)
>        It just is inferior to any dex in like every way.

Ah, might as well just make it a list of exchanges. This is probably why most token sites only link to exchanges.

**Comment by soulthunk** [comment]
please delete
